### PR TITLE
Random operation

### PR DESCRIPTION
**Pull request by rodrigouroz**
Hey

I loved this idea and implemented it (https://github.com/tomdionysus/foaas/issues/84).

Let me know if you like it.

Rod

### CODE REVIEW

**Comment by v6** [comment]
// , I like the new tests. Why isn't this all in one commit, though?

**Comment by rodrigouroz** [comment]
Sorry, I'm new to git. I'll squash it if that helps.

**Comment by v6** [comment]
// , Eh, if you want to. I was just wondering if it was a choice.

**Comment by rodrigouroz** [comment]
Yeah, I'll just leave it as it is then :-/

**Comment by zfjagann** [comment]
I :+1: it!

**Comment by rodrigouroz** [comment]
I'm glad you like it!
The more operations are added the more funny it will become :wink:

**Comment by tomdionysus** [comment]
@rodrigouroz sorry I've taken so long to get back on this. It's cool, the only problem is that it pretty much rewrites every operation. I don't mean to piss on your work at all - great effort - but tbh I'd really be happier with something less intrusive. I'd like to work on it with you though.

**Comment by tomdionysus** [comment]
@rodrigouroz do you still want to do this?

**Pull request closed without merging**
