### PR TITLE
added file for Legend Russ Hanneman

### PR DESCRIPTION
**Pull request by AkashSarda**
Added line "This Guy Fucks!" by Legendary Russ Hanneman from Silicon Valley

### CODE REVIEW

**Comment by AkashSarda** [comment]
@tomdionysus : can you please approve it and merge it?

**Comment by tomdionysus** [comment]
> @tomdionysus : can you please approve it and merge it?

It'll need a spec before I'll merge it - please write one (copy one of the existing ones).

**Comment by tomdionysus** [comment]
Still needs a spec, please update or i'll have to close.

**Comment by tomdionysus** [comment]
Sorry, If you still want it merged please write a spec and resubmit.

**Pull request closed without merging**
