### PR TITLE
added gr8 quote

### PR DESCRIPTION
**Pull request by antilights**
https://twitter.com/zaynmalik/status/433012329803169792

### CODE REVIEW

**Comment by tomdionysus** [comment]
Nice one, fix spec and I'll merge.

**Comment by antilights** [comment]
Fixed!

**Comment by antilights** [comment]
Just kidding, didn't fix it yet, please hold

**Comment by tomdionysus** [comment]
I have merged this, but renaming & squashing your commits/title to be less l33t has confused github. 0.1.7 with your resource will be online in half an hour.

**Comment by antilights** [comment]
Oh whoops, sorry! First time committing from a forked repository and still a complete newb, haha. Thanks for letting me know!

**Comment by tomdionysus** [comment]
Hey no probs at all, we were all new once. You're best being quite descriptive in commit messages/PR titles, and squashing your commits in a PR. Nice work and welcome to Github :)

**Pull request closed without merging**
