### PR TITLE
Removed the retard option to close #107

### LINKED ISSUE #107: Retard? Really?
It seems rather odd that I have to bring up the fact that calling someone a retard or fucktard is uncool. It's a blight on an otherwise wonderful site.

### PR DESCRIPTION
**Pull request by robotmachine**

### CODE REVIEW

**Comment by jungshadow** [comment]
:+1:

(Personally, I'm sad this even had to happen @robotmachine, but thanks for doing it)

**Comment by karenetheridge** [comment]
:-1:

**Comment by SwooshyCueb** [comment]
:+1:

**Comment by shadowcat-mst** [comment]
So, shall we replace it with 'moron'? Or 'idiot'? Or 'slow'? How far back do we need to go along the euphemism treadmill before we're safe?

Should we remove 'bad' as well because its etymology apparently involved criticising men for being effeminate a few centuries ago?

**Comment by SwooshyCueb** [comment]
I'm not currently inclined to debate this sort of thing in a github pull request, but personally I'd like to stay away from 'slow' as well.

I vote in favor of replacing 'Fucktard' with 'Fucknugget'. Doesn't contribute to any negative social stigmas that I'm aware of.

**Comment by dha** [comment]
Although I'm not convinced this isn't a slippery slope as indicated by @shadowcat-mst, I don't think replacing Fucktard with Fucknugget is terribly problematic as, in this context, it appears to convey the same sentiment.

**Comment by jungshadow** [comment]
I'm fine with @SwooshyCueb's idea of replacing the endpoint with /nugget or similar, but that could be handled in a separate PR. Would this be fine to purely cover the removal?

**Comment by AnUnknownMiner** [comment]
This operation can be changed to mean something else that doesn't ruin the context and your feelings. The idea @shadowcat-mst put is acceptable.

**Comment by philip2156** [comment]
I'd also vote for `/dumbfuck` to repalce it hah

**Comment by theromulans** [comment]
:+1: Would be nice to have a replacement rather than a straight up removal.

**Comment by philip2156** [comment]
I would not only vote for /dumbfuck as the replacement (unless its offensive as well? I'm Australian, not a lot offends me.) but I will merge it if changed in this PR

**Comment by mrsmn** [comment]
:-1: really people? really?

**Comment by robotmachine** [comment]
This is not a free speech slippery slope. This is simply removing something that is mean to someone who is not the target for the sake of laziness. If more people want it than don't, then it stays. I am doing what I feel is the right thing.

So sayeth the dude: You're not wrong, Walter. You're just an asshole.

**Comment by robotmachine** [comment]
I have no desire to replace this with anything. Someone else is welcome to take up that task.

**Comment by robotmachine** [comment]
I wrote too many feelings out [on the issue here](https://github.com/tomdionysus/foaas/issues/107#issuecomment-154857544).

**Comment by jungshadow** [comment]
> I think this removal requires the addition of some documentation of the guidelines for political correctness. For instance, we'd need to make it clear not to add the word "idiot", as well.

@v6 Not to speak for @robotmachine, but my impression is that this PR isn't about creating guidelines–which should be a longer discussion in another issue and I agree that it would be helpful–it's purely about removing one endpoint that is offensive to a community of people. There may be other instances of overtly offensive references, but, for the time being, it should be fine for these updates to happen organically.

> Plus, it would need regression tests to see whether more offensive words have been reintroduced.

While testing for overtly offensive words may be beneficial, I believe catching many of these sorts of issues is going to be a human process.

> For instance, I understand that the words "master," "dumb" and "slave", while used innocuously in the technical community as words for replication, are also quite offensive to the disadvantaged.

Possibly more evidence why the technical community feels exclusionary and isolating to many people.

I'm really surprised and disheartened that anyone is willing to push back on this change. It fine to be irreverent and humorous, but not hurtful/hateful.

**Comment by robotmachine** [comment]
@jungshadow The purpose of v6's comment is to prove that any effort to make a change like this would require loads of back-end work and process because if it is worth removing now then we must ensure it never happens again.

It is identical to the argument that banning guns won't work because criminals don't follow the law. ie. if it isn't going to be 100% effective then it has failed and shouldn't be attempted.

**Comment by AnUnknownMiner** [comment]
"... any effort to make a change like this would require loads of back-end work and process because if it is worth removing now then we must ensure it never happens again."

Well, it would be nice to not have to repeat this process every time someone is offended or wants an operation removed. Better now than later.

**Comment by kvannotten** [comment]
:-1: this PC stuff is getting out of hand tbh

**Comment by atomboulian** [comment]
:-1: "Fuck off" is offensive to everyone. It is meant to be an offensive service. It does not discriminate against any particular type of person; it treats every person the same. Certain persons are not exempt from mean comments directly or indirectly. I'm with @kvannotten.

**Comment by karenetheridge** [comment]
is "fuck off" discriminatory against asexual people?

**Comment by atomboulian** [comment]
well played @karenetheridge :smirk:

**Comment by philip2156** [comment]
@atomboulian @karenetheridge :+1:

**Comment by surdu** [comment]
:-1:

**Comment by RealDolos** [comment]
:-1: 
I identify as a retard and feel offended that people say my identify is offensive.
My pronouns are: tard/tardo

On an unrelated note, @jungshadow looks too white to have a nick name like this, I smell some sweet, sweet cultural appropriation

**Comment by robotmachine** [comment]
Are you fucking kidding me with this shit, @RealDolos? https://twitter.com/dolosthegreat/status/696198317848526848

I'm sorry that you are so fragile that the slightest disagreement makes you go ragepost on Twitter. 
http://foaas.com/bucket/robotmachine

**Comment by RealDolos** [comment]
@robotmachine Some people just cannot take a "thank you" I guess...
Also look who is raging now xD

**Comment by robotmachine** [comment]
You're right, @RealDolos. Thank you for being you. It would be nice if you'd at least be good enough <3 my tweets or something you adorable little fucknugget, you.

> Oh wait, that's homophobic I suppose. You should file an issue to have it removed...
I didn't say it had to be gay cocks you were choking on. They can be fake for all I care. My main concern is just that several cocks or cock-like implements find their way in to your general esophageal area.

**Comment by ChlorideCull** [comment]
>I didn't say it had to be gay cocks you were choking on. They can be fake for all I care. My main concern is just that several cocks or cock-like implements find their way in to your general esophageal area.

Well, @robotmachine, as a homosexual, i find it offensive that you believe such a thing is a punishment.

In all seriousness though, :-1:, this is a service meant to offend everyone, and it clearly does.

**Comment by masochist** [comment]
This is pretty fucking ironic. I would like to direct people in favor of this change to kindly [fuck off](http://foaas.com/off/masochist).

**Comment by tomdionysus** [comment]
All things considered, foaas.com isn't PC, and as has been repeatedly pointed out, it's _meant_ to be offensive in a lighthearted and ironic way, and if you're easily offended you probably shouldn't be anywhere near it, so I think i'll keep it as it is.

**Comment by v6** [comment]
// , Apparently my thoughtful, correctly *languaged*, supportive comment, with helpful suggestions for how to work out such problems by protecting the gentle denizens of Github from hate speech, has been removed from the record. 

I can't imagine what anyone would think we'd gain by its removal.

**Pull request closed without merging**
