### PR TITLE
added dockerfile

### PR DESCRIPTION
**Pull request by ruebenramirez**
use by building and then running:
    docker build -t foaas .
    docker run --name foaas -d -p 5000:5000 foaas

### CODE REVIEW

**Comment by SyntaxStacks** [comment]
+1
I'd like to see foaas clustered on CoreOS using fleet in the near future

**Comment by bighappyface** [comment]
@SyntaxStacks fuck-off :smile_cat:

**Comment by SyntaxStacks** [comment]
That's the spirit @bighappyface

**Comment by k-pom** [comment]
:+1:

**Comment by bighappyface** [comment]
I meant http://foaas.com/off/john/david

**Comment by xzased** [comment]
:+1:

**Comment by vaughnjavier** [comment]
+1

**Comment by philipmuir** [comment]
:+1:

**Pull request merged**
