### PR TITLE
load bootstrap css file over appropriate protocol

### PR DESCRIPTION
**Pull request by philipmuir**
@tomdionysus

### CODE REVIEW

**Comment by tomdionysus** [comment]
Does this not fuck out with a big honking 'some resources are insecure' on some browsers?

**Comment by philipmuir** [comment]
It does right now in my browser when visiting https://foaas.com

**Comment by philipmuir** [comment]
Mixed Content: The page at 'https://foaas.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css'.
This request has been blocked; the content must be served over HTTPS.

**Comment by tomdionysus** [comment]
Or, I could learn to read a fucking diff

**Pull request merged**
